// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCiZXyurxqkVcbGNVihBrn24YddStQyg',
    appId: '1:161646514333:web:b890d477b605910c3d8474',
    messagingSenderId: '161646514333',
    projectId: 'call-app-f357d',
    authDomain: 'call-app-f357d.firebaseapp.com',
    storageBucket: 'call-app-f357d.firebasestorage.app',
    measurementId: 'G-KK0P0CFDV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXXIGkCbe5lnwV2jg77TgRx3SdjG4iGH0',
    appId: '1:161646514333:android:fd9eb301cc4d71c43d8474',
    messagingSenderId: '161646514333',
    projectId: 'call-app-f357d',
    storageBucket: 'call-app-f357d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu42_y8HWpSHZYcgpnNHSuuJDIGMjcNno',
    appId: '1:161646514333:ios:30e65c3d4a1ded9d3d8474',
    messagingSenderId: '161646514333',
    projectId: 'call-app-f357d',
    storageBucket: 'call-app-f357d.firebasestorage.app',
    iosBundleId: 'com.example.callApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu42_y8HWpSHZYcgpnNHSuuJDIGMjcNno',
    appId: '1:161646514333:ios:30e65c3d4a1ded9d3d8474',
    messagingSenderId: '161646514333',
    projectId: 'call-app-f357d',
    storageBucket: 'call-app-f357d.firebasestorage.app',
    iosBundleId: 'com.example.callApp',
  );
}
